/**
 * tree-data.js
 * Master graph coordinates, nodes, and branching logic
 * for the Infinite Decision Canvas plane.
 */

export const DECISION_TREE_NODES = [
  {
    id: 'n_start',
    stageId: 0,
    x: 450,
    y: 60,
    width: 280,
    type: 'start',
    title: 'START: Idea / Problem',
    subtitle: 'Where every venture originates',
    description: 'Diagnose what you actually have before taking irreversible steps. Do not write code or incorporate yet.',
    rule: 'Do the next thing that removes the biggest uncertainty.',
    action: 'Audit current status against the 10 starting situations.'
  },
  {
    id: 'n_founder_setup',
    stageId: 1,
    x: 450,
    y: 200,
    width: 280,
    type: 'process',
    title: 'Founder & Co-Founder Setup',
    subtitle: 'Capabilities & Roles',
    description: 'Identify capability gaps. If permanent, evaluate co-founders. Test working relationship before equity lock. Vesting (4 yrs, 1 yr cliff) & IP assignment.',
    rule: 'Never give away equity for skills obtainable through contractors or advisors.',
    action: 'Draft co-founder memorandum with vesting & IP assignment.'
  },
  {
    id: 'n_problem_def',
    stageId: 2,
    x: 450,
    y: 350,
    width: 280,
    type: 'process',
    title: 'Define Customer & Problem',
    subtitle: 'Problem Discovery',
    description: 'Write: For [customer], when [situation occurs], [problem] causes [consequence]. Ensure the consequence is urgent, frequent, or costly.',
    rule: 'If customer is vague, narrow customer. If problem is vague, interview users.',
    action: 'Complete the 4-part problem definition formula.'
  },
  {
    id: 'n_gate_real_problem',
    stageId: 2,
    x: 470,
    y: 500,
    width: 240,
    type: 'decision',
    title: 'Is This a Real Problem?',
    subtitle: 'Decision Gate #1',
    description: 'Do prospective customers already spend time, energy, or money trying to solve or work around this issue?',
    yesTarget: 'n_cust_discovery',
    noTarget: 'n_stop_change_prob'
  },
  {
    id: 'n_stop_change_prob',
    stageId: 2,
    x: 820,
    y: 500,
    width: 260,
    type: 'stop',
    title: 'STOP / PIVOT: Change Problem',
    subtitle: 'Refine Segment or Problem',
    description: 'If people do not care enough to change behavior or spend budget, building a solution is futile. Pivot to a different segment or acute pain.',
    rule: 'Do not attempt to persuade people to care about a problem they do not have.',
    action: 'Return to Stage 2 with a new customer segment or different workflow.'
  },
  {
    id: 'n_cust_discovery',
    stageId: 3,
    x: 450,
    y: 670,
    width: 280,
    type: 'process',
    title: 'Customer Discovery Interviews',
    subtitle: 'Mom Test Principles',
    description: 'Conduct 15-20 interviews asking about past behavior: "What did you do the last time this happened?" Avoid hypothetical questions like "Would you buy this?"',
    rule: 'Opinions are worthless. Commitment of time, data, or money is truth.',
    action: 'Run interviews and rank signals along the Customer Evidence Ladder.'
  },
  {
    id: 'n_market_comp',
    stageId: 4,
    x: 450,
    y: 820,
    width: 280,
    type: 'process',
    title: 'Market & Competition Mapping',
    subtitle: 'Alternatives & Switching Costs',
    description: 'Map direct, indirect, manual (Excel/pen), and "do nothing" options. Calculate bottom-up TAM, SAM, and realistic SOM.',
    rule: 'Your primary competitor is almost always the status quo / "do nothing".',
    action: 'Construct competitive landscape matrix with switching barriers.'
  },
  {
    id: 'n_support_choice',
    stageId: 5,
    x: 100,
    y: 820,
    width: 280,
    type: 'support',
    title: 'Support Path Evaluation',
    subtitle: 'Pre-Incubator / Incubator / Grant',
    description: 'Match support program to your actual bottleneck: Need labs/workspace? Incubator. Need early mentoring? Pre-incubator. Research/deep-tech? Grants.',
    rule: 'Never join a program for prestige if it distracts from talking to customers.',
    action: 'Audit whether your current constraint requires structured support.'
  },
  {
    id: 'n_gate_meaningful_pain',
    stageId: 3,
    x: 470,
    y: 970,
    width: 240,
    type: 'decision',
    title: 'Evidence of Meaningful Pain?',
    subtitle: 'Decision Gate #2',
    description: 'Did discovery reveal deep frustration, active budget, or critical time loss that demands a better alternative?',
    yesTarget: 'n_solution_valprop',
    noTarget: 'n_stop_change_prob'
  },
  {
    id: 'n_solution_valprop',
    stageId: 6,
    x: 450,
    y: 1140,
    width: 280,
    type: 'process',
    title: 'Solution & Value Proposition',
    subtitle: '10x Measurable Outcome',
    description: 'Define: "For [customer], we help them [outcome] by [solution], unlike [alternative], because [differentiation]."',
    rule: 'Focus on measurable outcomes: 5x faster, 80% cheaper, or zero risk.',
    action: 'Formulate quantifiable value proposition statement.'
  },
  {
    id: 'n_validation_tests',
    stageId: 7,
    x: 450,
    y: 1290,
    width: 280,
    type: 'process',
    title: 'Validation Experiments',
    subtitle: 'Test Before Code',
    description: 'Sequence: Interview -> Prototype -> Landing Page -> Concierge Service -> Pre-Sale -> Paid Pilot. Test the single riskiest assumption first.',
    rule: 'If a hypothesis can be tested without writing code, test without code.',
    action: 'Run cheapest experiment to test willingness to adopt/pay.'
  },
  {
    id: 'n_gate_adopt_pay',
    stageId: 7,
    x: 470,
    y: 1440,
    width: 240,
    type: 'decision',
    title: 'Will Users Commit / Pay?',
    subtitle: 'Decision Gate #3',
    description: 'Did prospective users pre-order, place deposits, sign Letters of Intent (LOIs), or commit hours of active testing time?',
    yesTarget: 'n_build_mvp',
    noTarget: 'n_pivot_value_prop'
  },
  {
    id: 'n_pivot_value_prop',
    stageId: 7,
    x: 820,
    y: 1440,
    width: 260,
    type: 'stop',
    title: 'PIVOT / ITERATE: Reframe Offer',
    subtitle: 'Assumption Failed',
    description: 'If people say "sounds interesting" but will not commit time or money, the value proposition or packaging is insufficient.',
    rule: 'Polite compliments indicate a lack of genuine urgency.',
    action: 'Re-interview respondents to uncover the true barrier to commitment.'
  },
  {
    id: 'n_build_mvp',
    stageId: 8,
    x: 450,
    y: 1610,
    width: 280,
    type: 'process',
    title: 'Build Smallest Useful MVP',
    subtitle: 'Core Workflow Only',
    description: 'Build only the single workflow that proves value. Cut all auxiliary features, profile customizations, and secondary settings.',
    rule: 'The MVP must test a critical assumption, not impress with feature count.',
    action: 'Ship bare minimum product to the first 5 eager pilot users.'
  },
  {
    id: 'n_gate_mvp_value',
    stageId: 8,
    x: 470,
    y: 1760,
    width: 240,
    type: 'decision',
    title: 'MVP Creates Real Value?',
    subtitle: 'Decision Gate #4',
    description: 'Do pilot users actually complete the core workflow and experience the promised measurable outcome?',
    yesTarget: 'n_first_customers',
    noTarget: 'n_iterate_mvp'
  },
  {
    id: 'n_iterate_mvp',
    stageId: 8,
    x: 820,
    y: 1760,
    width: 260,
    type: 'process',
    title: 'ITERATE: Fix Core Product UX',
    subtitle: 'Remove Friction',
    description: 'Analyze session logs and exit interviews. Is onboarding too confusing? Is the core outcome failing technically? Strip down and rebuild the core path.',
    rule: 'Do not add new features to fix a product whose core workflow does not work.',
    action: 'Watch 5 users attempt onboarding live without speaking.'
  },
  {
    id: 'n_first_customers',
    stageId: 10,
    x: 450,
    y: 1930,
    width: 280,
    type: 'process',
    title: 'Acquire First Paying Customers',
    subtitle: 'Direct Founder Sales',
    description: 'Leverage warm network, targeted cold outreach (50-100 ICP leads), community participation, and direct founder demos to close first 5-10 accounts.',
    rule: 'Do things that do not scale at the start. Personally onboard every customer.',
    action: 'Conduct founder demos and convert pilots into paid contracts.'
  },
  {
    id: 'n_outreach_system',
    stageId: 9,
    x: 100,
    y: 1930,
    width: 280,
    type: 'process',
    title: 'Targeted Outreach Engine',
    subtitle: 'Outbound Discovery & Pilots',
    description: 'Build curated ICP list -> Personalize around specific pain triggers -> Multi-touch cadence (days 1, 4, 8, 14) -> Book discovery calls.',
    rule: 'Never send mass spam blasts. Send 50 highly personalized messages.',
    action: 'Draft and launch 4-touch outbound sequence.'
  },
  {
    id: 'n_gate_retention',
    stageId: 28,
    x: 470,
    y: 2090,
    width: 240,
    type: 'decision',
    title: 'Do Customers Retain?',
    subtitle: 'Decision Gate #5',
    description: 'Do paying customers stay active, renew subscriptions, or make repeat orders over 30, 60, and 90 days?',
    yesTarget: 'n_economics_model',
    noTarget: 'n_fix_retention'
  },
  {
    id: 'n_fix_retention',
    stageId: 28,
    x: 820,
    y: 2090,
    width: 260,
    type: 'stop',
    title: 'STOP: Churn Crisis',
    subtitle: 'Leaky Bucket',
    description: 'Acquiring more users while retention is broken burns money and reputation. Immediately halt acquisition marketing and diagnose churn.',
    rule: 'Never pour more water into a leaky bucket.',
    action: 'Call every churned user personally to identify why they stopped.'
  },
  {
    id: 'n_economics_model',
    stageId: 12,
    x: 450,
    y: 2260,
    width: 280,
    type: 'process',
    title: 'Business Model & Unit Economics',
    subtitle: 'LTV, CAC, Gross Margins',
    description: 'Answer the 10 business model questions. Calculate CAC, Gross Margin (>65% for software), and LTV. Ensure LTV/CAC > 3x and Payback < 12 months.',
    rule: 'A business cannot make up for negative unit economics with volume.',
    action: 'Build bottom-up contribution margin sheet.'
  },
  {
    id: 'n_gate_repeatable_gtm',
    stageId: 29,
    x: 470,
    y: 2420,
    width: 240,
    type: 'decision',
    title: 'Can Acquisition Repeat?',
    subtitle: 'Decision Gate #6',
    description: 'Can you acquire new customers predictably at acceptable CAC through at least 1 proven scalable channel?',
    yesTarget: 'n_capital_path',
    noTarget: 'n_iterate_channels'
  },
  {
    id: 'n_iterate_channels',
    stageId: 29,
    x: 820,
    y: 2420,
    width: 260,
    type: 'process',
    title: 'Test New GTM Channels',
    subtitle: 'Channel Discovery',
    description: 'Test one channel at a time: SEO, partner co-marketing, outbound sales, community, paid search, or product referrals. Measure CAC by channel.',
    rule: 'Master one dominant acquisition channel before spreading resources thin.',
    action: 'Run a 30-day single-channel acquisition sprint.'
  },
  {
    id: 'n_capital_path',
    stageId: 18,
    x: 450,
    y: 2590,
    width: 280,
    type: 'support',
    title: 'Capital & Financing Strategy',
    subtitle: 'Bootstrap vs Angels vs VC',
    description: 'Evaluate the 12 funding sources: If revenue can fund expansion, bootstrap. If venture-scale with high growth speed, raise Seed/VC with clear 18-month milestone.',
    rule: 'Never raise capital without knowing the exact value inflection milestone it unlocks.',
    action: 'Define required capital and select primary funding source.'
  },
  {
    id: 'n_incorporation_legal',
    stageId: 20,
    x: 450,
    y: 2750,
    width: 280,
    type: 'process',
    title: 'Company Formation & Legal Setup',
    subtitle: 'Entity, IP, Banking, Tax',
    description: 'Incorporate (e.g. Delaware C-Corp), formalize founder vesting, sign full IP assignment agreements, open business banking, configure accounting & compliance.',
    rule: 'Never commingle personal and corporate finances.',
    action: 'Execute formal incorporation and corporate governance.'
  },
  {
    id: 'n_eng_foundations',
    stageId: 24,
    x: 100,
    y: 2750,
    width: 280,
    type: 'process',
    title: 'Engineering & DevOps Foundations',
    subtitle: 'CI/CD, Monitoring, Backups',
    description: 'Set up automated test suites, CI/CD deployment pipeline, structured logging, synthetic uptime alerts, daily database backups, and MFA security.',
    rule: 'An unverified database backup is not a backup.',
    action: 'Run disaster recovery restore drill and lock main Git branch.'
  },
  {
    id: 'n_gate_scale_ready',
    stageId: 36,
    x: 470,
    y: 2920,
    width: 240,
    type: 'decision',
    title: 'Is Scaling Justified?',
    subtitle: 'Decision Gate #7',
    description: 'Are all 10 scaling readiness questions satisfied (repeatable acquisition, stable delivery, positive unit economics, 6+ month runway)?',
    yesTarget: 'n_hire_systematize',
    noTarget: 'n_stop_premature_scale'
  },
  {
    id: 'n_stop_premature_scale',
    stageId: 36,
    x: 820,
    y: 2920,
    width: 260,
    type: 'stop',
    title: 'STOP: Premature Scaling',
    subtitle: 'Consolidate Systems',
    description: 'Scaling an unstable, leaky product with high burn is the primary cause of startup collapse. Fix unit economics and operations first.',
    rule: 'Premature scaling magnifies operational flaws 100-fold.',
    action: 'Consolidate operations, document SOPs, and maintain cash runway.'
  },
  {
    id: 'n_hire_systematize',
    stageId: 35,
    x: 450,
    y: 3090,
    width: 280,
    type: 'process',
    title: 'Hire, Automate & Systematize',
    subtitle: 'Standard Operating Procedures',
    description: 'Document standard SOPs for sales, support, and release. Hire only for strategic capacity bottlenecks. Build 30-60-90 day scorecards.',
    rule: 'Write the process before hiring someone to execute it.',
    action: 'Draft core operating procedures and hire for proven bottlenecks.'
  },
  {
    id: 'n_sustainable_company',
    stageId: 41,
    x: 450,
    y: 3260,
    width: 280,
    type: 'success',
    title: 'SUSTAINABLE COMPANY',
    subtitle: 'Continuous Operating Loop',
    description: 'Run weekly founder reviews and monthly assumption audits. Maintain institutional memory via Decision Logs. Keep testing what you do not know.',
    rule: 'The company is never finished: Observe -> Hypothesize -> Experiment -> Decide -> Improve.',
    action: 'Operate the continuous founder rhythm.'
  }
];

export const DECISION_TREE_EDGES = [
  { from: 'n_start', to: 'n_founder_setup', label: 'Evaluate team' },
  { from: 'n_founder_setup', to: 'n_problem_def', label: 'Define pain' },
  { from: 'n_problem_def', to: 'n_gate_real_problem', label: 'Verify' },
  { from: 'n_gate_real_problem', to: 'n_cust_discovery', label: 'YES: Real pain' },
  { from: 'n_gate_real_problem', to: 'n_stop_change_prob', label: 'NO: Trivial / ignored' },
  { from: 'n_stop_change_prob', to: 'n_problem_def', label: 'New hypothesis' },
  { from: 'n_cust_discovery', to: 'n_market_comp', label: 'Analyze alts' },
  { from: 'n_cust_discovery', to: 'n_support_choice', label: 'Evaluate help' },
  { from: 'n_market_comp', to: 'n_gate_meaningful_pain', label: 'Validate' },
  { from: 'n_support_choice', to: 'n_solution_valprop', label: 'Guided path' },
  { from: 'n_gate_meaningful_pain', to: 'n_solution_valprop', label: 'YES: Severe pain' },
  { from: 'n_gate_meaningful_pain', to: 'n_stop_change_prob', label: 'NO: Weak signal' },
  { from: 'n_solution_valprop', to: 'n_validation_tests', label: 'Design tests' },
  { from: 'n_validation_tests', to: 'n_gate_adopt_pay', label: 'Measure commitment' },
  { from: 'n_gate_adopt_pay', to: 'n_build_mvp', label: 'YES: Strong commitment' },
  { from: 'n_gate_adopt_pay', to: 'n_pivot_value_prop', label: 'NO: Polite interest only' },
  { from: 'n_pivot_value_prop', to: 'n_solution_valprop', label: 'Reframe value' },
  { from: 'n_build_mvp', to: 'n_gate_mvp_value', label: 'Ship to 5 pilots' },
  { from: 'n_gate_mvp_value', to: 'n_first_customers', label: 'YES: Solves pain' },
  { from: 'n_gate_mvp_value', to: 'n_iterate_mvp', label: 'NO: Friction / failure' },
  { from: 'n_iterate_mvp', to: 'n_build_mvp', label: 'Refactor workflow' },
  { from: 'n_outreach_system', to: 'n_first_customers', label: 'Channel pipeline' },
  { from: 'n_first_customers', to: 'n_gate_retention', label: 'Measure 90d usage' },
  { from: 'n_gate_retention', to: 'n_economics_model', label: 'YES: Retains well' },
  { from: 'n_gate_retention', to: 'n_fix_retention', label: 'NO: Users churn' },
  { from: 'n_fix_retention', to: 'n_build_mvp', label: 'Fix core value loop' },
  { from: 'n_economics_model', to: 'n_gate_repeatable_gtm', label: 'Test scale' },
  { from: 'n_gate_repeatable_gtm', to: 'n_capital_path', label: 'YES: Repeatable' },
  { from: 'n_gate_repeatable_gtm', to: 'n_iterate_channels', label: 'NO: Unpredictable' },
  { from: 'n_iterate_channels', to: 'n_outreach_system', label: 'Refine channel' },
  { from: 'n_capital_path', to: 'n_incorporation_legal', label: 'Formalize' },
  { from: 'n_incorporation_legal', to: 'n_eng_foundations', label: 'Infra setup' },
  { from: 'n_incorporation_legal', to: 'n_gate_scale_ready', label: 'Assess gates' },
  { from: 'n_eng_foundations', to: 'n_gate_scale_ready', label: 'Production ready' },
  { from: 'n_gate_scale_ready', to: 'n_hire_systematize', label: 'YES: All gates pass' },
  { from: 'n_gate_scale_ready', to: 'n_stop_premature_scale', label: 'NO: Leaky / fragile' },
  { from: 'n_stop_premature_scale', to: 'n_economics_model', label: 'Fix economics' },
  { from: 'n_hire_systematize', to: 'n_sustainable_company', label: 'Continuous loop' }
];
